# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

#Setup the orbs
orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - store_artifacts:
          path: ~/project/build
          destination: build
  deploy:
    docker:
      - image: cimg/deploy:2023.05
    resource_class: small
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt update;
            sudo apt install lftp;
      - run: 
          name: add host to known values
          command: |
            for ip in $(dig @8.8.8.8 $HOSTNAME +short); do ssh-keyscan $HOSTNAME,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run:
          name: Deploy via SFTP
          command: |
            mkdir ~/.ssh;
            lftp sftp://$USERNAME:$PASSWORD@$HOSTNAME -e "mirror -R build/ /reabelx/2023/; quit";

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy_reabelx:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master # only deploy when on master
